stages:
  - build

variables:
  RUSTFLAGS: "-D warnings"
  CARGO_HOME: cache

cache:
  paths:
    - cache/
    - target/

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true
